# Generated by Django 4.2.7 on 2024-11-27 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.CharField(max_length=255)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_handler.menu')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_restriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_handler.dietaryrestriction')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_handler.menuitem')),
            ],
            options={
                'unique_together': {('menu_item', 'dietary_restriction')},
            },
        ),
    ]
