# Generated by Django 4.2.7 on 2024-11-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handler', '0003_fooditem_fooditemrestriction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='price',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
